### ISSUE TITLE
Có cách nào không cần sử dụng PREFIX không bác?

### ISSUE THREAD

**Issue by Luongzz** [XaviaTeam/facebook-bot-chatgpt#2]

**Comment by RFS-ADRENO** [comment]
Thử thay đổi index.js thành như này xem có vừa ý không

```js
import axios from "axios";
import { Client } from "fca-utils";
import { Configuration, OpenAIApi } from "openai";

const config = new Configuration({
    apiKey: process.env.OPENAI_KEY,
});

const openai = new OpenAIApi(config);

const client = new Client({
    prefix: process.env.PREFIX,
    ignoreMessageInCommandEvent: true,
});

client.openServer(process.env.PORT);
client.loginWithAppState(process.env.APPSTATE);
client.on("ready", (_, bid) =>
    console.log("Logged in as", bid, `[${process.env.PREFIX}]`)
);

client.on("message", (message) => {
    if (message.args.length == 0) return;
    const command = {
        name: message.args[0].toLowerCase(),
        commandArgs: message.args.slice(1),
        message,
    };

    if (command.name === "ai") {
        openai
            .createChatCompletion({
                model: "gpt-3.5-turbo",
                max_tokens: 1000,
                n: 1,
                messages: [
                    {
                        role: "user",
                        content: command.commandArgs.join(" "),
                    },
                ],
            })
            .then(async (res) => {
                try {
                    const parsedContent = (
                        await axios.get(
                            `https://xva-api.up.railway.app/api/extractgpt?content=${encodeURIComponent(
                                res.data.choices[0].message.content
                            )}&maxCharacterPerLine=6000`
                        )
                    ).data;
                    const result = parsedContent.data.result;

                    for (let i = 0; i < result.length; i++) {
                        await command.message[i === 0 ? "reply" : "send"](
                            result[i]
                        );
                        await new Promise((resolve) =>
                            setTimeout(resolve, 500)
                        );
                    }
                } catch (e) {
                    console.error(e.response.data);
                    command.message.reply("An error occurred!");
                }
            })
            .catch((e) => {
                console.error(e.response.data);
                command.message.reply("An error occurred!");
            });
    }

    if (command.name === "create") {
        openai
            .createImage({
                prompt: command.commandArgs.join(" "),
                size: "512x512",
                response_format: "url",
            })
            .then((res) => {
                command.message.sendAttachment(res.data.data[0].url);
            })
            .catch((e) => {
                console.error(e.response.data);
                command.message.reply("An error occurred!");
            });
    }
});

client.on("error", (e) => {
    console.error("login error");
    console.error(e);
});
```

**Comment by Luongzz** [comment]
> Thử thay đổi index.js thành như này xem có vừa ý không
> 
> ```js
> import axios from "axios";
> import { Client } from "fca-utils";
> import { Configuration, OpenAIApi } from "openai";
> 
> const config = new Configuration({
>     apiKey: process.env.OPENAI_KEY,
> });
> 
> const openai = new OpenAIApi(config);
> 
> const client = new Client({
>     prefix: process.env.PREFIX,
>     ignoreMessageInCommandEvent: true,
> });
> 
> client.openServer(process.env.PORT);
> client.loginWithAppState(process.env.APPSTATE);
> client.on("ready", (_, bid) =>
>     console.log("Logged in as", bid, `[${process.env.PREFIX}]`)
> );
> 
> client.on("message", (message) => {
>     if (message.args.length == 0) return;
>     const command = {
>         name: message.args[0].toLowerCase(),
>         commandArgs: message.args.slice(1),
>         message,
>     };
> 
>     if (command.name === "ai") {
>         openai
>             .createChatCompletion({
>                 model: "gpt-3.5-turbo",
>                 max_tokens: 1000,
>                 n: 1,
>                 messages: [
>                     {
>                         role: "user",
>                         content: command.commandArgs.join(" "),
>                     },
>                 ],
>             })
>             .then(async (res) => {
>                 try {
>                     const parsedContent = (
>                         await axios.get(
>                             `https://xva-api.up.railway.app/api/extractgpt?content=${encodeURIComponent(
>                                 res.data.choices[0].message.content
>                             )}&maxCharacterPerLine=6000`
>                         )
>                     ).data;
>                     const result = parsedContent.data.result;
> 
>                     for (let i = 0; i < result.length; i++) {
>                         await command.message[i === 0 ? "reply" : "send"](
>                             result[i]
>                         );
>                         await new Promise((resolve) =>
>                             setTimeout(resolve, 500)
>                         );
>                     }
>                 } catch (e) {
>                     console.error(e.response.data);
>                     command.message.reply("An error occurred!");
>                 }
>             })
>             .catch((e) => {
>                 console.error(e.response.data);
>                 command.message.reply("An error occurred!");
>             });
>     }
> 
>     if (command.name === "create") {
>         openai
>             .createImage({
>                 prompt: command.commandArgs.join(" "),
>                 size: "512x512",
>                 response_format: "url",
>             })
>             .then((res) => {
>                 command.message.sendAttachment(res.data.data[0].url);
>             })
>             .catch((e) => {
>                 console.error(e.response.data);
>                 command.message.reply("An error occurred!");
>             });
>     }
> });
> 
> client.on("error", (e) => {
>     console.error("login error");
>     console.error(e);
> });
> ```

ý mình là chat với nó như một người bình thường không thông qua câu lệnh gì hết

**Comment by RFS-ADRENO** [comment]
```js
import axios from "axios";
import { Client } from "fca-utils";
import { Configuration, OpenAIApi } from "openai";

const config = new Configuration({
    apiKey: process.env.OPENAI_KEY,
});

const openai = new OpenAIApi(config);

const client = new Client({
    prefix: process.env.PREFIX,
    ignoreMessageInCommandEvent: false,
});

client.openServer(process.env.PORT);
client.loginWithAppState(process.env.APPSTATE);
client.on("ready", (_, bid) =>
    console.log("Logged in as", bid, `[${process.env.PREFIX}]`)
);

client.on("message", (message) => {
    if (message.body.length == 0) return;
    if (!message.body.startsWith("create ")) {
        openai
            .createChatCompletion({
                model: "gpt-3.5-turbo",
                max_tokens: 1000,
                n: 1,
                messages: [
                    {
                        role: "user",
                        content: message.body.trim(),
                    },
                ],
            })
            .then(async (res) => {
                try {
                    const parsedContent = (
                        await axios.get(
                            `https://xva-api.up.railway.app/api/extractgpt?content=${encodeURIComponent(
                                res.data.choices[0].message.content
                            )}&maxCharacterPerLine=6000`
                        )
                    ).data;
                    const result = parsedContent.data.result;

                    for (let i = 0; i < result.length; i++) {
                        await message[i === 0 ? "reply" : "send"](result[i]);
                        await new Promise((resolve) =>
                            setTimeout(resolve, 500)
                        );
                    }
                } catch (e) {
                    console.error(e.response.data);
                    message.reply("An error occurred!");
                }
            })
            .catch((e) => {
                console.error(e.response.data);
                message.reply("An error occurred!");
            });
    } else {
        const prompt = message.body.slice(7).trim();
	if (prompt.length == 0) return;

        openai
            .createImage({
                prompt: prompt,
                size: "512x512",
                response_format: "url",
            })
            .then((res) => {
                message.sendAttachment(res.data.data[0].url);
            })
            .catch((e) => {
                console.error(e.response.data);
                message.reply("An error occurred!");
            });
    }
});

client.on("error", (e) => {
    console.error("login error");
    console.error(e);
});
```

như này thì sao?

**Comment by Luongzz** [comment]
> ```js
> import axios from "axios";
> import { Client } from "fca-utils";
> import { Configuration, OpenAIApi } from "openai";
> 
> const config = new Configuration({
>     apiKey: process.env.OPENAI_KEY,
> });
> 
> const openai = new OpenAIApi(config);
> 
> const client = new Client({
>     prefix: process.env.PREFIX,
>     ignoreMessageInCommandEvent: false,
> });
> 
> client.openServer(process.env.PORT);
> client.loginWithAppState(process.env.APPSTATE);
> client.on("ready", (_, bid) =>
>     console.log("Logged in as", bid, `[${process.env.PREFIX}]`)
> );
> 
> client.on("message", (message) => {
>     if (message.body.length == 0) return;
>     if (!message.body.startsWith("create ")) {
>         openai
>             .createChatCompletion({
>                 model: "gpt-3.5-turbo",
>                 max_tokens: 1000,
>                 n: 1,
>                 messages: [
>                     {
>                         role: "user",
>                         content: message.body.trim(),
>                     },
>                 ],
>             })
>             .then(async (res) => {
>                 try {
>                     const parsedContent = (
>                         await axios.get(
>                             `https://xva-api.up.railway.app/api/extractgpt?content=${encodeURIComponent(
>                                 res.data.choices[0].message.content
>                             )}&maxCharacterPerLine=6000`
>                         )
>                     ).data;
>                     const result = parsedContent.data.result;
> 
>                     for (let i = 0; i < result.length; i++) {
>                         await message[i === 0 ? "reply" : "send"](result[i]);
>                         await new Promise((resolve) =>
>                             setTimeout(resolve, 500)
>                         );
>                     }
>                 } catch (e) {
>                     console.error(e.response.data);
>                     message.reply("An error occurred!");
>                 }
>             })
>             .catch((e) => {
>                 console.error(e.response.data);
>                 message.reply("An error occurred!");
>             });
>     } else {
>         const prompt = message.body.slice(7).trim();
> 	if (prompt.length == 0) return;
> 
>         openai
>             .createImage({
>                 prompt: prompt,
>                 size: "512x512",
>                 response_format: "url",
>             })
>             .then((res) => {
>                 message.sendAttachment(res.data.data[0].url);
>             })
>             .catch((e) => {
>                 console.error(e.response.data);
>                 message.reply("An error occurred!");
>             });
>     }
> });
> 
> client.on("error", (e) => {
>     console.error("login error");
>     console.error(e);
> });
> ```
> 
> như này thì sao?

cám ơn bác đã ngon nghẻ
