### ISSUE TITLE
API sập rồi bác ơi

### ISSUE THREAD

**Issue by Luongzz** [XaviaTeam/facebook-bot-chatgpt#3]

**Comment by RFS-ADRENO** [comment]
Lên lại rồi nha

**Comment by Luongzz** [comment]
> Lên lại rồi nha

cám ơn bác

**Comment by Luongzz** [comment]
API lại bị time out rồi bác

**Comment by RFS-ADRENO** [comment]
sống rồi, cơ chết suốt nhỉ, để rảnh tôi bê hàm xử lý lên đây luôn, khỏi phụ thuôc api nữa

**Comment by Luongzz** [comment]
nó lại sập tiếp rồi bác ~~
